### ISSUE TITLE
EpilogueError: internal error 

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [dchester/epilogue#233]
Any idea, why i'm getting this error message? 
**EpilogueError: internal error**
    at node_modules/epilogue/lib/Controllers/base.js:193:28
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by dimitrypo** [comment]
This library is abandoned. This one https://github.com/tommybananas/finale seems to be a working fork
